services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chatdb
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
